sensors:
   - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
     point_cloud_topic: /camera/depth/points
     max_range: 2.5
     point_subsample: 1
     padding_offset: 0.09
     padding_scale: 1.0
     filtered_cloud_topic: filtered_cloud
